/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import base_link from './base_link.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(base_link);
  return [{type:'raw', geometry:nodes.base_link.geometry, material: nodes.base_link.material}]
  
}
useGLTF.preload(base_link)