/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import BASE_LEFT_COVER_1 from './BASE_LEFT_COVER_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(BASE_LEFT_COVER_1);
  return [{type:'raw', geometry:nodes.BASE_LEFT_COVER_1.geometry, material: nodes.BASE_LEFT_COVER_1.material}]
  
}
useGLTF.preload(BASE_LEFT_COVER_1)