/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import DRIVE_TRACK_LEFT_1 from './DRIVE_TRACK_LEFT_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(DRIVE_TRACK_LEFT_1);
  return [{type:'raw', geometry:nodes.DRIVE_TRACK_LEFT_1.geometry, material: nodes.DRIVE_TRACK_LEFT_1.material}]
  
}
useGLTF.preload(DRIVE_TRACK_LEFT_1)