/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import EYE_LENS_1 from './EYE_LENS_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(EYE_LENS_1);
  return [{type:'raw', geometry:nodes.EYE_LENS_1.geometry, material: nodes.EYE_LENS_1.material}]
  
}
useGLTF.preload(EYE_LENS_1)