/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import FRONT_RIGHT_WHEEL_1 from './FRONT_RIGHT_WHEEL_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(FRONT_RIGHT_WHEEL_1);
  return [{type:'raw', geometry:nodes.FRONT_RIGHT_WHEEL_1.geometry, material: nodes.FRONT_RIGHT_WHEEL_1.material}]
  
}
useGLTF.preload(FRONT_RIGHT_WHEEL_1)