/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import HEAD_1 from './HEAD_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(HEAD_1);
  return [{type:'raw', geometry:nodes.HEAD_1.geometry, material: nodes.HEAD_1.material}]
  
}
useGLTF.preload(HEAD_1)