/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import REAR_LEFT_WHEEL_1 from './REAR_LEFT_WHEEL_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(REAR_LEFT_WHEEL_1);
  return [{type:'raw', geometry:nodes.REAR_LEFT_WHEEL_1.geometry, material: nodes.REAR_LEFT_WHEEL_1.material}]
  
}
useGLTF.preload(REAR_LEFT_WHEEL_1)