/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Torso_1 from './Torso_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(Torso_1);
  return [{type:'raw', geometry:nodes.Torso_1.geometry, material: nodes.Torso_1.material}]
  
}
useGLTF.preload(Torso_1)