/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import VISOR_GLASS_1 from './VISOR_GLASS_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(VISOR_GLASS_1);
  return [{type:'raw', geometry:nodes.VISOR_GLASS_1.geometry, material: nodes.VISOR_GLASS_1.material}]
  
}
useGLTF.preload(VISOR_GLASS_1)