const FaceFilenameMap = {
    
  "e_Sleeping": "e_Sleeping.jpg",
  "e_SleepingZZZ": "e_SleepingZZZ.jpg",
  "e_Contempt": "e_Contempt.jpg",
  "e_ContentLeft": "e_ContentLeft.jpg",
  "e_ContentRight": "e_ContentRight.jpg",
  "e_Disoriented": "e_Disoriented.jpg",
  "e_EcstacyHilarious": "e_EcstacyHilarious.jpg",
  "e_EcstacyStarryEyed": "e_EcstacyStarryEyed.jpg",
  "e_JoyGoofy": "e_JoyGoofy.jpg",
  "e_JoyGoofy2": "e_JoyGoofy2.jpg",
  "e_JoyGoofy3": "e_JoyGoofy3.jpg",
  "e_Love": "e_Love.jpg",
  "e_Rage": "e_Rage.jpg",
  "e_Rage2": "e_Rage2.jpg",
  "e_Rage3": "e_Rage3.jpg",
  "e_Rage4": "e_Rage4.jpg",
  "e_RemorseShame": "e_RemorseShame.jpg",
  "eyes_acceptance": "eyes_acceptance.jpg",
  "eyes_admiration": "eyes_admiration.jpg",
  "eyes_amazement": "eyes_amazement.jpg",
  "eyes_anger": "eyes_anger.jpg",
  "eyes_annoyed": "eyes_annoyed.jpg",
  "eyes_anticipation": "eyes_anticipation.png",
  "eyes_apprehension": "eyes_apprehension.jpg",
  "eyes_apprehension_1": "eyes_apprehension_1.jpg",
  "eyes_boredom": "eyes_boredom.jpg",
  "eyes_default": "eyes_default.jpg",
  "eyes_disgust": "eyes_disgust.jpg",
  "eyes_distraction": "eyes_distraction.gif",
  "eyes_ecstasy_frame_1": "eyes_ecstasy_frame_1.jpg",
  "eyes_ecstasy_frame_2": "eyes_ecstasy_frame_2.jpg",
  "eyes_fear": "eyes_fear.jpg",
  "eyes_grief": "eyes_grief.jpg",
  "eyes_interest": "eyes_interest.jpg",
  "eyes_joy": "eyes_joy.jpg",
  "eyes_loathing": "eyes_loathing.jpg",
  "eyes_pensiveness": "eyes_pensiveness.jpg",
  "eyes_rage": "eyes_rage.jpg",
  "eyes_sad": "eyes_sad.jpg",
  "eyes_serenity": "eyes_serenity.jpg",
  "eyes_surprise": "eyes_surprise.png",
  "eyes_terror": "eyes_terror.jpg",
  "eyes_trust": "eyes_trust.jpg",
  "eyes_vigilance": "eyes_vigilance.jpg",
};

const FaceFilenameLookup = (path) => FaceFilenameMap[path];
export { FaceFilenameMap, FaceFilenameLookup };