/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import BASE_FRONT_GRILL_1 from './BASE_FRONT_GRILL_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(BASE_FRONT_GRILL_1);
  return [{type:'raw', geometry:nodes.BASE_FRONT_GRILL_1.geometry, material: nodes.BASE_FRONT_GRILL_1.material, scale: [1,1,1], rotation: [0,0,0]}]
  
}
useGLTF.preload(BASE_FRONT_GRILL_1)