/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Battery_1 from './Battery_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(Battery_1);
  return [{type:'raw', geometry:nodes.Battery_1.geometry, material: nodes.Battery_1.material, scale: [1,1,1], rotation: [0,0,0]}]
  
}
useGLTF.preload(Battery_1)