/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import mesh from "./eyes_sad.glb"
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF(mesh)
  return [{type:'raw', geometry:nodes.Plane.geometry, material: materials['Material.001'], scale: [1,1,1], rotation: [0,0,0]}]
}

useGLTF.preload(mesh)