/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import FACE_1 from './FACE_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(FACE_1);
  return [{type:'raw', geometry:nodes.FACE_1.geometry, material: nodes.FACE_1.material, scale: [1,1,1], rotation: [0,0,0]}]
  
}
useGLTF.preload(FACE_1)