/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import HEAD_VENT_RIGHT_1 from './HEAD_VENT_RIGHT_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(HEAD_VENT_RIGHT_1);
  return [{type:'raw', geometry:nodes.HEAD_VENT_RIGHT_1.geometry, material: nodes.HEAD_VENT_RIGHT_1.material, scale: [1,1,1], rotation: [0,0,0]}]
  
}
useGLTF.preload(HEAD_VENT_RIGHT_1)