/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import MIDDLE_LEFT_WHEEL_1 from './MIDDLE_LEFT_WHEEL_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(MIDDLE_LEFT_WHEEL_1);
  return [{type:'raw', geometry:nodes.MIDDLE_LEFT_WHEEL_1.geometry, material: nodes.MIDDLE_LEFT_WHEEL_1.material, scale: [1,1,1], rotation: [0,0,0]}]
  
}
useGLTF.preload(MIDDLE_LEFT_WHEEL_1)