/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import NECK_GLOBE_BASE_1 from './NECK_GLOBE_BASE_1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(NECK_GLOBE_BASE_1);
  return [{type:'raw', geometry:nodes.NECK_GLOBE_BASE_1.geometry, material: nodes.NECK_GLOBE_BASE_1.material, scale: [1,1,1], rotation: [0,0,0]}]
  
}
useGLTF.preload(NECK_GLOBE_BASE_1)